// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: wallet.proto

package wallet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Wallet service

type WalletService interface {
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...client.CallOption) (*GetWalletResponse, error)
}

type walletService struct {
	c    client.Client
	name string
}

func NewWalletService(name string, c client.Client) WalletService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "wallet"
	}
	return &walletService{
		c:    c,
		name: name,
	}
}

func (c *walletService) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...client.CallOption) (*GetWalletResponse, error) {
	req := c.c.NewRequest(c.name, "Wallet.GetWallet", in)
	out := new(GetWalletResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Wallet service

type WalletHandler interface {
	GetWallet(context.Context, *GetWalletRequest, *GetWalletResponse) error
}

func RegisterWalletHandler(s server.Server, hdlr WalletHandler, opts ...server.HandlerOption) error {
	type wallet interface {
		GetWallet(ctx context.Context, in *GetWalletRequest, out *GetWalletResponse) error
	}
	type Wallet struct {
		wallet
	}
	h := &walletHandler{hdlr}
	return s.Handle(s.NewHandler(&Wallet{h}, opts...))
}

type walletHandler struct {
	WalletHandler
}

func (h *walletHandler) GetWallet(ctx context.Context, in *GetWalletRequest, out *GetWalletResponse) error {
	return h.WalletHandler.GetWallet(ctx, in, out)
}
